name: pubsub
version: 1.0.1
author: Dj Gilcrease <digitalxero@gmail.com>
description: Async hierarchical pubsub library, modeled after https://github.com/KanbanSolutions/jquery-pubsub
homepage: https://github.com/Digitalxero/dart-pubsub
documentation: https://github.com/Digitalxero/dart-pubsub
dependencies:
  logging: '>=0.8.1 <0.8.2'
dev_dependencies:
  unittest: any
